spring:
  application:
    name: demo-graphql
  datasource:
    url: jdbc:postgresql://localhost:5433/demo_graphql
    username: demo
    password: demo
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate.jdbc.time_zone: UTC
  graphql:
    path: /graphql
  flyway:
    enabled: true
  docker:
    compose:
      file: compose.yaml
management:
  endpoints:
    web:
      exposure:
        include: health
logging:
  level:
    root: INFO
